# AUTO-GENERATED by auto_append_cart_tests.py
# API: PATCH /terminals/{terminal_id}/description  (update_terminal_description)
# AUTO-GENERATED: func_name=update_terminal_description
# 生成日時: 2026-03-10 09:34:26
#
# 【対応する test-review.md 改善方案】
#   P0 : Service 層の単体テスト追加（AsyncMock を使用）
#
# ⚠️  このファイルは自動生成されたものです。
#     pytest.skip() を削除し、Service 層のビジネスロジックを
#     AsyncMock / MagicMock を使ってテストしてください。

import pytest
from unittest.mock import AsyncMock, MagicMock, patch


# ─────────────────────────────────────────────
# フィクスチャ
# ─────────────────────────────────────────────

@pytest.fixture
def mock_cart_service():
    """
    CartService の AsyncMock を生成するフィクスチャ。
    Repository 層・外部通信を全てスタブ化することで、
    Service 層のビジネスロジックのみを独立して検証できる。

    使い方：
      mock_service = AsyncMock()
      mock_service.some_method.return_value = expected_value
    """
    service = AsyncMock()
    service.terminal_info = MagicMock()
    service.terminal_info.tenant_id = "test-tenant"
    service.terminal_info.store_code = "0001"
    service.terminal_info.terminal_no = 1
    service.cart_id = "test-cart-id"
    return service


# ─────────────────────────────────────────────
# 単体テスト（Unit Test）
# ─────────────────────────────────────────────

@pytest.mark.asyncio
async def test_update_terminal_description_unit_success(mock_cart_service):
    """
    【単体テスト | 正常系 | P0】
    Service 層メソッドの正常動作を検証する。

    PATCH /terminals/{terminal_id}/description
        Update terminal description

    TODO:
      1. mock_cart_service の対応メソッドに return_value を設定する
      2. Service メソッドを呼び出す
      3. 戻り値・呼び出し引数をアサートする（assert_called_once_with 等）
    """
    pytest.skip(
        "AUTO-GENERATED: Service 層の正常系単体テストを実装してください（P0 対応）。"
        f"API: PATCH /terminals/{terminal_id}/description"
    )


@pytest.mark.asyncio
async def test_update_terminal_description_unit_validation_error(mock_cart_service):
    """
    【単体テスト | バリデーションエラー | P0】
    不正な入力に対してカスタム例外が発生することを検証する。

    テスト観点（P0-1 の手順に準拠）：
      - 業務ルール違反時に適切な HTTPException / カスタム例外が raise されるか
      - @pytest.mark.parametrize を使って複数の境界値パターンを網羅する
    """
    pytest.skip(
        "AUTO-GENERATED: バリデーションエラーの単体テストを実装してください（P0 対応）。"
        f"API: PATCH /terminals/{terminal_id}/description"
    )
