"""
auto_append_tests.py  (旧称: auto_append_cart_tests.py)
==========================================================
全サービス API 変更 → テスト骨架自動追加スクリプト

【概要】
services/<service>/app/api/v1/ 配下の API ルートを静的解析し、
services/<service>/tests/ 配下の既存テストと比較して、
未カバーのエンドポイントに対しテスト骨架ファイルを自動生成する。

【test-review.md 改善方案との対応】
  P0 → Unit テスト骨架（AsyncMock 使用, tests/unit/*_unit_auto.py）
  P1 → シナリオ+異常系テスト骨架（tests/scenario/*_scenario_auto.py）

【使い方】
  cd /home/gaocuiping/myself/kugelpos-stpos-docs-new

  # 全サービス対象
  python scripts/auto_append_tests.py --all

  # 特定サービスのみ
  python scripts/auto_append_tests.py --service cart
  python scripts/auto_append_tests.py --service terminal

  # ドライラン（ファイル作成なし、確認のみ）
  python scripts/auto_append_tests.py --all --dry-run
  python scripts/auto_append_tests.py --service cart --dry-run
"""

import os
import re
import ast
import argparse
from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional


# ─────────────────────────────────────────────
# 設定
# ─────────────────────────────────────────────
PROJECT_ROOT = "/home/gaocuiping/myself/kugelpos-stpos-docs-new"

SERVICES_CONFIG = {
    "cart": {
        "api_dir": "services/cart/app/api/v1",
        "tests_dir": "services/cart/tests",
        "service_id": "CT",
        "base_path": "/api/v1",
    },
    "terminal": {
        "api_dir": "services/terminal/app/api/v1",
        "tests_dir": "services/terminal/tests",
        "service_id": "TM",
        "base_path": "/api/v1",
    },
    "account": {
        "api_dir": "services/account/app/api/v1",
        "tests_dir": "services/account/tests",
        "service_id": "AC",
        "base_path": "/api/v1",
    },
    "master-data": {
        "api_dir": "services/master-data/app/api/v1",
        "tests_dir": "services/master-data/tests",
        "service_id": "MD",
        "base_path": "/api/v1",
    },
    "report": {
        "api_dir": "services/report/app/api/v1",
        "tests_dir": "services/report/tests",
        "service_id": "RP",
        "base_path": "/api/v1",
    },
    "stock": {
        "api_dir": "services/stock/app/api/v1",
        "tests_dir": "services/stock/tests",
        "service_id": "SK",
        "base_path": "/api/v1",
    },
    "journal": {
        "api_dir": "services/journal/app/api/v1",
        "tests_dir": "services/journal/tests",
        "service_id": "JN",
        "base_path": "/api/v1",
    },
}

# 自動生成タグ（同一スクリプトが再実行された時の識別子）
AUTO_GEN_TAG = "# AUTO-GENERATED by auto_append_cart_tests.py"

# ─────────────────────────────────────────────
# データクラス
# ─────────────────────────────────────────────
@dataclass
class ApiEndpoint:
    """API エンドポイント情報"""
    func_name: str
    method: str          # GET / POST / PATCH / DELETE / PUT
    path: str
    docstring: str
    source_file: str
    # path から抽出したパスパラメータ一覧（例：cart_id, lineNo）
    path_params: list[str] = field(default_factory=list)

    def __post_init__(self):
        self.path_params = re.findall(r'\{(\w+)\}', self.path)


# ─────────────────────────────────────────────
# Step 1: API 解析
# ─────────────────────────────────────────────
def extract_api_endpoints(api_dir_abs: str) -> list[ApiEndpoint]:
    """
    api_dir_abs 配下の .py ファイルから @router.xxx デコレータを解析して
    ApiEndpoint リストを返す。

    正規表現パターン：
      @router.<method>("<path>", ...)
      async def <func_name>(...):
          \"\"\"<docstring>\"\"\"
    """
    endpoints = []

    if not os.path.isdir(api_dir_abs):
        print(f"  [WARN] API ディレクトリが見つかりません: {api_dir_abs}")
        return endpoints

    pattern = re.compile(
        r'@router\.(?P<method>get|post|put|patch|delete)\s*\(\s*["\'](?P<path>[^"\']+)["\']'
        r'.*?'
        r'async\s+def\s+(?P<func_name>\w+)\s*\(',
        re.DOTALL | re.IGNORECASE,
    )

    for filename in sorted(os.listdir(api_dir_abs)):
        if not filename.endswith(".py") or filename == "__init__.py":
            continue

        filepath = os.path.join(api_dir_abs, filename)
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
        except Exception as e:
            print(f"  [ERROR] ファイル読み込み失敗: {filepath}: {e}")
            continue

        for m in pattern.finditer(content):
            func_name = m.group("func_name")
            method = m.group("method").upper()
            path = m.group("path")

            # docstring 抽出（関数定義の直後）
            # func_name 後ろの本文スライスから取得
            func_pos = m.end()
            remainder = content[func_pos:]
            docstring = _extract_docstring_after_func(remainder)

            endpoints.append(ApiEndpoint(
                func_name=func_name,
                method=method,
                path=path,
                docstring=docstring,
                source_file=filename,
            ))
            print(f"  [API] {method:6s} {path}  →  {func_name}()")

    return endpoints


def _extract_docstring_after_func(text: str) -> str:
    """関数定義直後の三重引用符ドキュメント文字列を抽出する"""
    # コロン + 空白/改行 + 三重引用符
    doc_pattern = re.compile(r':\s*"""(.*?)"""', re.DOTALL)
    m = doc_pattern.search(text[:2000])  # 先頭 2000 文字以内に限定
    if m:
        lines = m.group(1).strip().splitlines()
        # 最初の非空行だけを返す
        for line in lines:
            line = line.strip()
            if line:
                return line
    return ""


# ─────────────────────────────────────────────
# Step 2: 既存テスト関数の収集
# ─────────────────────────────────────────────
def collect_existing_test_funcs(tests_dir_abs: str) -> tuple[set[str], set[str], set[str]]:
    """
    tests_dir_abs 配下（再帰）の全 .py ファイルから以下を収集する：
      - 定義済みテスト関数名
      - AUTO-GENERATED タグが管理する API func_name
      - テストファイル内で呼び出されている URL パスパターン
        （例: /api/v1/carts, /carts/{cart_id}/lineItems）の断片集合

    戻り値：
      (existing_test_funcs, covered_api_funcs, url_fragments_by_file)
    """
    existing_test_funcs: set[str] = set()   # def test_xxx の xxx
    covered_api_funcs: set[str] = set()     # AUTO-GENERATED タグの func_name
    # テストファイル全体に出現する URL パス断片 (スラッシュ区切りのセグメント集合)
    all_url_segments: set[str] = set()

    # HTTP クライアント呼び出し行から URL を抽出するパターン
    # 例: .post("/api/v1/carts"), .get(f"/api/v1/carts/{cart_id}")
    url_call_pattern = re.compile(
        r'\.(get|post|patch|put|delete)\s*\(\s*f?[\'"](/[^\'"\s{)]+)',
        re.IGNORECASE,
    )

    for root, dirs, files in os.walk(tests_dir_abs):
        dirs[:] = [d for d in dirs if d != "__pycache__"]
        for fname in files:
            if not fname.endswith(".py"):
                continue
            fpath = os.path.join(root, fname)
            try:
                with open(fpath, "r", encoding="utf-8") as f:
                    content = f.read()
            except Exception:
                continue

            # def test_xxx を収集
            for m in re.finditer(r'^\s*(?:async\s+)?def\s+(test_\w+)\s*\(', content, re.MULTILINE):
                existing_test_funcs.add(m.group(1))

            # AUTO-GENERATED タグが管理する API func_name を収集
            for m in re.finditer(r'# AUTO-GENERATED:\s*func_name=(\w+)', content):
                covered_api_funcs.add(m.group(1))

            # HTTP 呼び出し URL のセグメントを収集
            for m in url_call_pattern.finditer(content):
                raw_path = m.group(2)
                # {variable} プレースホルダを {var} に正規化
                normalized = re.sub(r'\{[^}]+\}', '{var}', raw_path)
                # パス全体と各末尾セグメントを登録
                all_url_segments.add(normalized)
                # クエリパラメータを除去
                base = normalized.split('?')[0]
                all_url_segments.add(base)

    print(f"\n  [INFO] 既存テスト関数: {len(existing_test_funcs)} 件")
    print(f"  [INFO] AUTO-GEN タグ済み API: {len(covered_api_funcs)} 件")
    print(f"  [INFO] 検出 URL パターン: {len(all_url_segments)} 件")
    return existing_test_funcs, covered_api_funcs, all_url_segments


def _is_api_covered(
    endpoint: ApiEndpoint,
    existing_test_funcs: set[str],
    covered_api_funcs: set[str],
    all_url_segments: set[str],
) -> bool:
    """
    API がテスト済みかどうかを判定する。

    判定ルール（優先順）：
      1. covered_api_funcs に func_name がある → 済み（AUTO-GEN タグ）
      2. existing_test_funcs に test_<func_name> / test_<func_name>_auto がある → 済み
      3. URL パターン一致：エンドポイントのパスが既存テスト内の HTTP 呼び出しに含まれる → 済み
         （例: /carts/{cart_id}/lineItems がテスト内で呼ばれている → add_items は済み）
    """
    fn = endpoint.func_name

    # ルール 1: AUTO-GEN タグ
    if fn in covered_api_funcs:
        return True

    # ルール 2: 関数名一致
    for candidate in [f"test_{fn}", f"test_{fn}_auto", f"test_{fn}_happy_path"]:
        if candidate in existing_test_funcs:
            return True

    # ルール 3: URL パターン一致
    # API パスの {xxx} プレースホルダを {var} に正規化して比較
    normalized_api_path = re.sub(r'\{[^}]+\}', '{var}', endpoint.path)
    # /api/v1 プレフィックスを付けたバージョンも比較
    prefixed = f"/api/v1{normalized_api_path}"

    if normalized_api_path in all_url_segments or prefixed in all_url_segments:
        return True

    # パス末尾セグメントでの部分一致（フラグメントレベル）
    # 例：/carts/{var}/lineItems/{var}/cancel が含まれるか
    path_segments = normalized_api_path.rstrip('/').split('/')
    # 末尾の固定セグメント（パラメータでない部分）で補助一致
    fixed_tail = '/'.join([s for s in path_segments if s and '{' not in s])
    if fixed_tail and len(fixed_tail) > 3:  # 短すぎる文字列は除外
        for seg in all_url_segments:
            if fixed_tail in seg:
                return True

    return False


# ─────────────────────────────────────────────
# Step 3: テスト骨架ファイル生成
# ─────────────────────────────────────────────
SCENARIO_TEMPLATE = '''{auto_gen_tag}
# API: {method} {path}  ({func_name})
# AUTO-GENERATED: func_name={func_name}
# 生成日時: {generated_at}
#
# 【対応する test-review.md 改善方案】
#   P1-4 : 未カバー API のシナリオテスト追加
#   P1-5 : 異常系（4xx/5xx）シナリオテスト追加
#
# ⚠️  このファイルは自動生成されたものです。
#     pytest.skip() を削除し、実際のテストロジックを実装してください。
#     実装完了後は、このコメントヘッダを適切なものに書き換えてください。

import pytest
from fastapi import status


# ─────────────────────────────────────────────
# 正常系テスト（Happy Path）
# ─────────────────────────────────────────────

@pytest.mark.asyncio
async def test_{func_name}_happy_path(http_client):
    """
    【正常系 | シナリオテスト】
    {method} {path}

    {docstring_block}

    TODO:
      1. 前提データ（cart_id / terminal_id 等）を準備する
      2. 必要なヘッダー（X-API-KEY / Authorization）を設定する
      3. エンドポイントへリクエストを送信する
      4. レスポンスコード・ボディの主要フィールドをアサートする
    """
    pytest.skip(
        "AUTO-GENERATED: 正常系テストを実装してください。"
        f"API: {method} {path}"
    )


# ─────────────────────────────────────────────
# 異常系テスト 4xx（P1-5 対応）
# ─────────────────────────────────────────────

@pytest.mark.asyncio
async def test_{func_name}_error_invalid_request(http_client):
    """
    【異常系 | 4xx クライアントエラー | P1-5】
    {method} {path}

    テスト観点：
      - 必須パラメータ欠落時の 422 エラー
      - 無効な ID による 404 エラー
      - 認証なしでの 401/403 エラー
      - 業務ルール違反時の 400/409 エラー
    """
    pytest.skip(
        "AUTO-GENERATED: 4xx 異常系テストを実装してください（P1-5 対応）。"
        f"API: {method} {path}"
    )


@pytest.mark.asyncio
async def test_{func_name}_error_server_error(http_client):
    """
    【異常系 | 5xx サーバーエラー | P1-5】
    {method} {path}

    テスト観点：
      - DB 切断・タイムアウト時に 500 が返却されるか
      - エラーレスポンスのフォーマット（success=False, code=500）が正しいか
    """
    pytest.skip(
        "AUTO-GENERATED: 5xx 異常系テストを実装してください（P1-5 対応）。"
        f"API: {method} {path}"
    )
'''

UNIT_TEMPLATE = '''{auto_gen_tag}
# API: {method} {path}  ({func_name})
# AUTO-GENERATED: func_name={func_name}
# 生成日時: {generated_at}
#
# 【対応する test-review.md 改善方案】
#   P0 : Service 層の単体テスト追加（AsyncMock を使用）
#
# ⚠️  このファイルは自動生成されたものです。
#     pytest.skip() を削除し、Service 層のビジネスロジックを
#     AsyncMock / MagicMock を使ってテストしてください。

import pytest
from unittest.mock import AsyncMock, MagicMock, patch


# ─────────────────────────────────────────────
# フィクスチャ
# ─────────────────────────────────────────────

@pytest.fixture
def mock_cart_service():
    """
    CartService の AsyncMock を生成するフィクスチャ。
    Repository 層・外部通信を全てスタブ化することで、
    Service 層のビジネスロジックのみを独立して検証できる。

    使い方：
      mock_service = AsyncMock()
      mock_service.some_method.return_value = expected_value
    """
    service = AsyncMock()
    service.terminal_info = MagicMock()
    service.terminal_info.tenant_id = "test-tenant"
    service.terminal_info.store_code = "0001"
    service.terminal_info.terminal_no = 1
    service.cart_id = "test-cart-id"
    return service


# ─────────────────────────────────────────────
# 単体テスト（Unit Test）
# ─────────────────────────────────────────────

@pytest.mark.asyncio
async def test_{func_name}_unit_success(mock_cart_service):
    """
    【単体テスト | 正常系 | P0】
    Service 層メソッドの正常動作を検証する。

    {method} {path}
    {docstring_block}

    TODO:
      1. mock_cart_service の対応メソッドに return_value を設定する
      2. Service メソッドを呼び出す
      3. 戻り値・呼び出し引数をアサートする（assert_called_once_with 等）
    """
    pytest.skip(
        "AUTO-GENERATED: Service 層の正常系単体テストを実装してください（P0 対応）。"
        f"API: {method} {path}"
    )


@pytest.mark.asyncio
async def test_{func_name}_unit_validation_error(mock_cart_service):
    """
    【単体テスト | バリデーションエラー | P0】
    不正な入力に対してカスタム例外が発生することを検証する。

    テスト観点（P0-1 の手順に準拠）：
      - 業務ルール違反時に適切な HTTPException / カスタム例外が raise されるか
      - @pytest.mark.parametrize を使って複数の境界値パターンを網羅する
    """
    pytest.skip(
        "AUTO-GENERATED: バリデーションエラーの単体テストを実装してください（P0 対応）。"
        f"API: {method} {path}"
    )
'''


def _build_docstring_block(docstring: str, indent: str = "    ") -> str:
    """docstring を複数行に整形する"""
    if not docstring:
        return f"{indent}API の docstring が取得できませんでした。ソースコードを参照してください。"
    return f"{indent}{docstring}"


def generate_test_files(
    endpoint: ApiEndpoint,
    tests_dir_abs: str,
    dry_run: bool = False,
) -> list[str]:
    """
    1 つの ApiEndpoint に対して 2 つのテストファイルを生成する：
      - tests/scenario/test_<func_name>_scenario_auto.py  （シナリオ+異常系）
      - tests/unit/test_<func_name>_unit_auto.py           （単体テスト）

    戻り値：生成したファイルパスのリスト
    """
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fn = endpoint.func_name
    docstring_block = _build_docstring_block(endpoint.docstring)

    common_vars = dict(
        auto_gen_tag=AUTO_GEN_TAG,
        func_name=fn,
        method=endpoint.method,
        path=endpoint.path,
        docstring_block=docstring_block,
        generated_at=generated_at,
    )

    # ── 出力先サブディレクトリを決定 ─────────────────────────
    unit_dir     = os.path.join(tests_dir_abs, "unit")
    scenario_dir = os.path.join(tests_dir_abs, "scenario")

    files_to_generate = [
        (scenario_dir, f"test_{fn}_scenario_auto.py", SCENARIO_TEMPLATE.format(**common_vars)),
        (unit_dir,     f"test_{fn}_unit_auto.py",     UNIT_TEMPLATE.format(**common_vars)),
    ]

    generated_paths = []
    for target_dir, filename, content in files_to_generate:
        # サブディレクトリが存在しない場合は作成
        os.makedirs(target_dir, exist_ok=True)
        init_file = os.path.join(target_dir, "__init__.py")
        if not os.path.exists(init_file):
            open(init_file, "w").close()

        filepath = os.path.join(target_dir, filename)
        rel_path = os.path.join(os.path.basename(target_dir), filename)

        if os.path.exists(filepath):
            print(f"  [SKIP] 既に存在します: {rel_path}")
            continue

        if dry_run:
            print(f"  [DRY-RUN] 生成予定: {rel_path}")
        else:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"  [NEW ] 生成しました: {rel_path} ✨")

        generated_paths.append(filepath)

    return generated_paths


# ─────────────────────────────────────────────
# Step 4: メイン処理
# ─────────────────────────────────────────────
def run(service_name: str, dry_run: bool = False):
    """指定サービスの API スキャン → テスト差分生成を実行する"""
    config = SERVICES_CONFIG.get(service_name)
    if not config:
        print(f"[ERROR] サービス '{service_name}' が設定に見つかりません。")
        return

    api_dir_abs   = os.path.join(PROJECT_ROOT, config["api_dir"])
    tests_dir_abs = os.path.join(PROJECT_ROOT, config["tests_dir"])

    print(f"\n{'='*60}")
    print(f"  サービス: {service_name}")
    print(f"  API  DIR: {api_dir_abs}")
    print(f"  TEST DIR: {tests_dir_abs}")
    print(f"  DRY RUN : {dry_run}")
    print(f"{'='*60}\n")

    # 1. API スキャン
    print("【STEP 1】API エンドポイントをスキャン中...")
    endpoints = extract_api_endpoints(api_dir_abs)
    print(f"\n  → {len(endpoints)} 件の API エンドポイントを検出\n")

    # 2. 既存テスト収集
    print("【STEP 2】既存テスト関数を収集中...")
    existing_test_funcs, covered_api_funcs, all_url_segments = collect_existing_test_funcs(tests_dir_abs)

    # 3. 差分計算 + 生成
    print("\n【STEP 3】差分計算 & テスト骨架生成...")
    uncovered = []
    for ep in endpoints:
        if _is_api_covered(ep, existing_test_funcs, covered_api_funcs, all_url_segments):
            print(f"  [OK  ] {ep.method:6s} {ep.path}  →  {ep.func_name}()  ✅ 既にカバー済み")
        else:
            print(f"  [NEW ] {ep.method:6s} {ep.path}  →  {ep.func_name}()  ❌ 未カバー → 生成対象")
            uncovered.append(ep)

    print(f"\n  未カバー: {len(uncovered)} / {len(endpoints)} エンドポイント")

    if not uncovered:
        print("\n  ✅ 全エンドポイントがカバー済みです。スキップします。")
        return

    print(f"\n【STEP 4】テストファイルを生成中... (dry_run={dry_run})")
    total_generated = []
    for ep in uncovered:
        print(f"\n  → {ep.func_name}() の骨架を生成:")
        generated = generate_test_files(ep, tests_dir_abs, dry_run=dry_run)
        total_generated.extend(generated)

    # サマリー
    print(f"\n{'='*60}")
    print(f"  完了！")
    print(f"  対象 API    : {len(endpoints)} 件")
    print(f"  カバー済み  : {len(endpoints) - len(uncovered)} 件  ✅")
    print(f"  新規生成    : {len(uncovered)} 件  ✨  ({len(total_generated)} ファイル)")
    if dry_run:
        print(f"  ※ DRY-RUN モードのため、実際のファイルは作成されていません。")
    print(f"{'='*60}\n")

    if not dry_run and total_generated:
        print("  次のステップ：")
        print("    1. 生成されたファイルを開き、pytest.skip() を実装に置き換えてください。")
        print("    2. pytest テストを実行して収集できることを確認してください：")
        print(f"       cd {os.path.dirname(tests_dir_abs)}")
        print(f"       pytest tests/ --collect-only 2>&1 | grep 'auto'")
        print()


def main():
    parser = argparse.ArgumentParser(
        description="全サービス API 変更に基づくテスト骨架自動追加スクリプト"
    )
    parser.add_argument(
        "--service",
        choices=list(SERVICES_CONFIG.keys()),
        help="対象サービス名（例: cart, terminal）",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="全サービスを対象にする",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="ドライラン：ファイルを作成せず確認のみ行う",
    )
    args = parser.parse_args()

    if args.all:
        # 全サービスを順番に処理
        for svc in SERVICES_CONFIG.keys():
            run(service_name=svc, dry_run=args.dry_run)
    elif args.service:
        run(service_name=args.service, dry_run=args.dry_run)
    else:
        # デフォルト: cart（後方互換性のため）
        run(service_name="cart", dry_run=args.dry_run)


if __name__ == "__main__":
    main()
